SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO  
WHERE NUM_PASS NOT BETWEEN 112 AND 160
ORDER BY NUM_PASS;

SELECT NOME, COGNOME, SESSO
FROM DBETL.ANAGRAFE_DIPENDENTI
WHERE TRIM(NOME) LIKE '_a%' AND TRIM(NOME) LIKE '%o';

SELECT MAX(NUM_PASS) AS MASSIMO, SUM(NUM_PASS) AS SOMMA, AVG(NUM_PASS) AS MEDIA, COUNT(*) AS CONTEGGIO_PASS
FROM DBETL.AEREO;

SELECT * FROM DBETL.ANAGRAFE_DIPENDENTI;


SELECT NOME, COGNOME, SESSO,
EXTRACT (MONTH FROM DT_NASC) AS MESE_NASCITA
FROM DBETL.ANAGRAFE_DIPENDENTI;
