SELECT I.* ,  O.*
FROM TB_IMPIEGATI I, TB_ORDINI O
WHERE I.ID_IMP = O.ID_IMP AND O.CLIENTE = 'Fiat'
ORDER BY I.NOME ASC;

--2
SELECT I.*,  O.*
FROM TB_IMPIEGATI I, TB_ORDINI O
WHERE I.ID_IMP = O.ID_IMP
AND EXTRACT(MONTH FROM O.DATA_ORDINE) = '2' 
AND EXTRACT(YEAR FROM O.DATA_ORDINE) = '2014'
ORDER BY O.CLIENTE  ASC;

--3
SELECT DISTINCT FN.ID_FORNITORE, FN.DENOMINAZIONE, P.IN_COMMERCIO
FROM MARKET_FORNITORI FN, MARKET_PRODOTTI P
WHERE P.ID_FORNITORE = FN.ID_FORNITORE
AND P.IN_COMMERCIO NOT LIKE 'N' 
OR P.IN_PRODUZIONE NOT LIKE 'N'
ORDER BY P.IN_COMMERCIO ASC;

--4
SELECT ID_LIBRO
FROM TB_02_LIBRI
INTERSECT
SELECT ID_LIBRO
FROM TB_02_PRESTITO_LIBRO
WHERE ID_LIBRO LIKE '%7';

--5
SELECT F.TITOLO, F.GENERE, P.DATA_PROIEZIONE
FROM FILM F, PROIEZIONI P
WHERE F.COD_FILM = P.COD_FILM
AND EXTRACT(MONTH FROM P.DATA_PROIEZIONE) IN ('12')
ORDER BY F.GENERE DESC;

--6
SELECT F.TITOLO, F.GENERE, S.CITTA
FROM FILM F, PROIEZIONI P, SALE S
WHERE F.COD_FILM = P.COD_FILM
AND P.COD_SALA = S.COD_SALA
AND S.CITTA LIKE 'Napoli'
AND EXTRACT(MONTH FROM P.DATA_PROIEZIONE) IN ('7', '8', '9')
ORDER BY F.GENERE ASC;

--7

SELECT F.TITOLO, A.COGNOME
FROM FILM F, RECITA R, ATTORI A
WHERE A.ID_ATT = R.ID_ATT
AND R.COD_FILM = F.COD_FILM
AND A.COGNOME LIKE '_i%'
ORDER BY F.TITOLO ASC;

--8
SELECT F.TITOLO, S.NOME_SALA , P.DATA_PROIEZIONE
FROM FILM F, PROIEZIONI P, SALE S
WHERE F.COD_FILM = P.COD_FILM
    AND P.COD_SALA = S.COD_SALA
AND P.DATA_PROIEZIONE BETWEEN '01/08/2004' AND '31/12/2008'
AND S.CITTA LIKE 'Roma'
ORDER BY F.TITOLO ASC, S.NOME_SALA DESC;

--9
SELECT LB.TITOLO, U.COGNOME
FROM TB_02_LIBRI LB, TB_02_PRESTITO_LIBRO P, TB_02_UTENTI U
WHERE P.ID_LIBRO = LB.ID_LIBRO
    AND U.ID_STUDENTE = P.ID_STUDENTE
AND U.COGNOME = 'Vallieri'
ORDER BY P.DT_INI_PRES ASC;

--10
SELECT U.NOME, U.COGNOME, LB.TITOLO
FROM TB_02_LIBRI LB, TB_02_PRESTITO_LIBRO P, TB_02_UTENTI U
WHERE P.ID_LIBRO = LB.ID_LIBRO
    AND U.ID_STUDENTE = P.ID_STUDENTE
AND P.DT_FIN_PRES IS NULL
ORDER BY P.ID_PRESTITO DESC, COGNOME ASC;

--11
SELECT DIP.COGNOME, DIP.NOME, U.NOME_UFFICIO
FROM DIPENDENTI DIP, UFFICI U
WHERE DIP.COD_UFF = U.COD_UFF
AND DIP.COGNOME BETWEEN 'D%' AND 'J%'
ORDER BY DIP.COGNOME ASC;

--12
SELECT D.COGNOME, D.NOME, U.COD_UFF, D.RUOLO
FROM DIPENDENTI D, UFFICI U 
WHERE D.COD_UFF = U.COD_UFF
AND U.COD_UFF BETWEEN 'A02'AND 'D22'
AND D.RUOLO NOT LIKE 'Magazziniere'
AND D.COGNOME LIKE 'A%'
ORDER BY U.NOME_UFFICIO, D.COGNOME, D.NOME;
--------------
SELECT D.COGNOME, D.NOME, U.COD_UFF, D.RUOLO
FROM DIPENDENTI D 
INNER JOIN UFFICI U ON D.COD_UFF = U.COD_UFF
AND U.COD_UFF BETWEEN 'A02'AND 'D22'
AND D.RUOLO NOT LIKE 'Magazziniere'
AND D.COGNOME LIKE 'A%'
ORDER BY U.NOME_UFFICIO, D.COGNOME, D.NOME;

--13
SELECT U.NOME_UFFICIO, D.COGNOME, U.RESP_UFF
FROM DIPENDENTI D, UFFICI U
WHERE D.COD_DIP = U.RESP_UFF
ORDER BY D.COGNOME ASC;

SELECT U.NOME_UFFICIO, D.COGNOME, U.RESP_UFF
FROM DIPENDENTI D INNER JOIN UFFICI U
ON D.COD_DIP = U.RESP_UFF
ORDER BY D.COGNOME ASC;


--14
SELECT T.COD_PROG, D.NOME, D.COGNOME
FROM DIPENDENTI D, TASK_DIPENDENTI T 
WHERE D.COD_DIP = T.COD_DIP
AND T.COD_PROG LIKE 'B%2'
ORDER BY T.COD_PROG , T.NUM_TASK;

------------------

SELECT T.COD_PROG, D.NOME, D.COGNOME
FROM DIPENDENTI D JOIN TASK_DIPENDENTI T ON D.COD_DIP = T.COD_DIP
WHERE T.COD_PROG LIKE 'B%2'
ORDER BY T.COD_PROG , T.NUM_TASK;

--15
SELECT DISTINCT D.COD_UFF, D.COGNOME, P.NOME_PROG, T.NUM_TASK
FROM DIPENDENTI D, PROGETTI P, TASK_DIPENDENTI T 
WHERE D.COD_DIP = T.COD_DIP
AND D.COD_UFF = P.COD_UFF
AND P.COD_PROG NOT BETWEEN 'A00' AND 'C01'
ORDER BY D.COD_UFF, D.COGNOME, T.NUM_TASK;


SELECT DISTINCT D.COD_UFF, D.COGNOME, P.NOME_PROG, T.NUM_TASK
FROM DIPENDENTI D INNER JOIN TASK_DIPENDENTI T
ON D.COD_DIP = T.COD_DIP
INNER JOIN PROGETTI P
ON D.COD_UFF = P.COD_UFF
WHERE P.COD_PROG NOT BETWEEN 'A00' AND 'C01'
ORDER BY D.COD_UFF, D.COGNOME, T.NUM_TASK;


SELECT *
FROM DIPENDENTI;

SELECT *
FROM TASK_DIPENDENTI;

SELECT * 
FROM PROGETTI;