--1
SELECT COGNOME , DT_NASCITA, BONUS, STIPENDIO
FROM DIPENDENTI
WHERE BONUS > 500
ORDER BY STIPENDIO ASC;

--2

SELECT COGNOME, NOME, COD_UFF
FROM DIPENDENTI
WHERE TRIM(NOME) LIKE '%i'
ORDER BY COD_UFF DESC, COGNOME ASC;

--3
--ho inserito anche nome per rendere la query più leggibile
SELECT DISTINCT NOME, LIVELLO_ISTRUZIONE
FROM DIPENDENTI
ORDER BY LIVELLO_ISTRUZIONE ASC;


--4
SELECT COD_DIP, COD_PROG
FROM TASK_DIPENDENTI
WHERE COD_DIP >= 100
AND COD_PROG BETWEEN 'I' AND 'N'
ORDER BY COD_PROG;


--5
SELECT COGNOME, STIPENDIO, BONUS
FROM DIPENDENTI
WHERE SESSO='U' AND DT_ASSUNZ BETWEEN '01/08/2023' AND '01/12/24'
ORDER BY COGNOME ASC;

--6
SELECT COGNOME, STIPENDIO, BONUS, COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 3000 AND BONUS > 400)
OR (BONUS > 500 AND COMMISSIONI < 300)
ORDER BY COGNOME ASC;

--7
SELECT NOME, COGNOME, STIPENDIO, BONUS, COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500 AND BONUS < 400 AND COMMISSIONI > 300) 
OR (STIPENDIO > 2500 AND BONUS > 500 AND COMMISSIONI > 300)
ORDER BY COGNOME ASC;


--8
SELECT COD_PROG, NUM_TASK, DT_INI_TASK, DT_FIN_TASK
FROM TASK_DIPENDENTI
WHERE COD_PROG LIKE 'A%' 
AND ID_TASK = 10 
OR (ID_TASK=80)
OR (ID_TASK=180)
ORDER BY NUM_TASK ASC;

--9
SELECT COD_UFF, RESP_UFF 
FROM UFFICI
WHERE TRIM(RESP_UFF) != '(null)'
ORDER BY RESP_UFF ASC;

--10
SELECT COGNOME, STIPENDIO, COMMISSIONI
FROM DIPENDENTI
WHERE (STIPENDIO > 2500) 
AND (EXTRACT(YEAR FROM DT_ASSUNZ) > 2022)
ORDER BY COGNOME ASC;

--11
SELECT COD_DIP, COGNOME, STIPENDIO, BONUS
FROM DIPENDENTI
WHERE BONUS BETWEEN 800 AND 900
ORDER BY BONUS ASC;

--12
SELECT COD_DIP, COGNOME, STIPENDIO, COD_UFF
FROM DIPENDENTI
WHERE COD_UFF BETWEEN 'A00' AND 'C01'
ORDER BY COGNOME ASC, COD_DIP DESC;

--13
SELECT COD_PROG, NOME_PROG
FROM PROGETTI
WHERE NOME_PROG LIKE '%Sviluppo%'
ORDER BY COD_PROG ASC;

--14
SELECT COD_UFF, NOME_UFFICIO
FROM UFFICI
WHERE COD_UFF LIKE '_1_'
ORDER BY COD_UFF DESC;


--15
SELECT COGNOME, NOME, INIZIALI, STIPENDIO
FROM DIPENDENTI
WHERE (RUOLO != 'Amministratore' AND RUOLO != 'Manager')
AND (INIZIALI != 'FL' AND  INIZIALI != 'TC')
AND (STIPENDIO BETWEEN 2500 AND 2630)
ORDER BY STIPENDIO DESC;

--16

SELECT NOME_SALA
FROM SALE
WHERE NOME_SALA LIKE '__A__A%'
ORDER BY NOME_SALA ASC;

--17
SELECT TITOLO, DATA_PROD    
FROM FILM
WHERE (TRIM(GENERE) = 'Drammatico')
AND (TRIM(NAZIONALITA) IN ('USA' , 'spagna'))
AND (TRIM(DATA_PROD) BETWEEN '01/01/2000' AND '31/12/2007')
ORDER BY DATA_PROD DESC;

--18
SELECT TITOLO, DATA_PROD, REGISTA 
FROM FILM
WHERE DATA_PROD BETWEEN '01/01/1997' AND '31/12/2001'
AND EXTRACT(MONTH FROM DATA_PROD) BETWEEN '4' AND '9'
ORDER BY TITOLO ASC;

--19
SELECT DISTINCT CITTA_PARTENZA
FROM VOLI
WHERE CITTA_ARRIVO = 'Roma'
ORDER BY CITTA_PARTENZA ASC;

--20
SELECT *
FROM AEROPORTI
WHERE NUM_PISTE IS NULL
ORDER BY CITTA_ARRIVO ASC;

--21
SELECT ID_VOLO, CITTA_PARTENZA, CITTA_ARRIVO, TIPO_AEREO
FROM VOLI
WHERE TIPO_AEREO IN ('E49I3', 'AZ94P', 'CK13L ')
AND (CITTA_PARTENZA = 'Milano') 
AND (CITTA_ARRIVO != 'Las Vegas' OR CITTA_ARRIVO != 'Vienna' OR CITTA_ARRIVO != 'Barcellona')
ORDER BY TIPO_AEREO ASC;

--22
SELECT COGNOME, NOME, NUM_TEL_INTERNO
FROM DIPENDENTI
WHERE EXTRACT(MONTH FROM DT_ASSUNZ) NOT IN ('3','6','9','12') 
AND STIPENDIO BETWEEN 1670 AND 2550
ORDER BY NOME DESC;

--23
SELECT COGNOME, NOME, DT_ASSUNZ
FROM DIPENDENTI
WHERE NOME NOT IN ('Mirco', 'Dario', 'Andrea', 'Daniele', 'Paolo')
AND EXTRACT(DAY FROM DT_ASSUNZ) BETWEEN 11 AND 14
ORDER BY DT_ASSUNZ DESC;

--24
SELECT ID_CLIENTE, DT_INI_PREN
FROM HOTEL_PREN
WHERE ID_CLIENTE IN (3,5,6) AND DURATA >= 4 AND DURATA <= 10
ORDER BY ID_CLIENTE ASC;

--25
SELECT COD_DIP, COGNOME, NOME, STIPENDIO
FROM DIPENDENTI
WHERE RUOLO LIKE '____e%'
ORDER BY COGNOME ASC;

--26

SELECT SUM(STIPENDIO) AS SOMMA_STIPENDI_UFF_B01
FROM DIPENDENTI
WHERE COD_UFF = 'B01';

--27
SELECT COUNT(*) AS TOTALE_DIPENDENTI
FROM DIPENDENTI
WHERE RUOLO LIKE '%Manager%' 
AND EXTRACT(MONTH FROM DT_ASSUNZ) IN ('2', '8')
AND NOME LIKE '%o%'
AND COMMISSIONI BETWEEN 200 AND 400;
 
 --28

SELECT MIN(STIPENDIO) AS STIPENDIO_MINIMO, MAX(STIPENDIO)AS STIPENDIO_MASSIMO , AVG(STIPENDIO) AS STIPENDIO_MEDIO
FROM DIPENDENTI
WHERE RUOLO LIKE '%Manager%' 
AND EXTRACT(MONTH FROM DT_ASSUNZ) IN ('2', '8', '9', '11', '12')
AND NOME LIKE '%o%'
AND COMMISSIONI BETWEEN 200 AND 400;