SELECT *
FROM DIPENDENTI;
-----------------
--1
SELECT COGNOME, NOME, DT_ASSUNZ, 'Per anno' AS TIPO_RICERCA
FROM dipendenti
WHERE EXTRACT(YEAR FROM DT_ASSUNZ) = 2021

UNION ALL

SELECT COGNOME, NOME, DT_ASSUNZ, 'Per mese' AS TIPO_RICERCA
FROM DIPENDENTI
WHERE EXTRACT(MONTH FROM DT_ASSUNZ) = 4

ORDER BY TIPO_RICERCA, COGNOME;



--2

SELECT NOME, COGNOME, 'PRIMA AUMENTO' AS DESCRIZIONE, STIPENDIO
FROM DIPENDENTI
WHERE RUOLO <>'Manager'
AND COD_UFF = 'D21'

UNION ALL

SELECT NOME, COGNOME,'DOPO AUMENTO' AS DESCRIZIONE, STIPENDIO * 1.10
FROM DIPENDENTI
WHERE RUOLO <> 'Manager'
AND COD_UFF = 'D21'
ORDER BY COGNOME, DESCRIZIONE; 



--------------------------------------

--ESERCIZIO NUM 3

--3
SELECT '1' AS TIPO, COD_UFF, 'UFFICIO' AS  INFO, NOME_UFFICIO AS NOME 
FROM UFFICI
WHERE COD_UFF IN ('A00', 'B01' , 'C01')

UNION ALL

SELECT '2' AS TIPO, COD_UFF,  COD_PROG AS INFO, NOME_PROG AS NOME
FROM PROGETTI
WHERE COD_UFF IN ('A00', 'B01' , 'C01')

UNION ALL

SELECT '3' AS TIPO , COD_UFF, COD_DIP AS INFO , COGNOME AS NOME 
FROM DIPENDENTI
WHERE COD_UFF IN ('A00', 'B01' , 'C01')
ORDER BY INFO ASC;




SELECT *
FROM UFFICI;